export const items = [
    {
      title: "Why do we use it?",
      text_1: "It is a long established fact that a reader will be distracted by the readable content",
      text_2: "It is a long established fact that a reader will be distracted by the readable content",
      text_3: "It is a long established fact that a reader will be distracted by the readable content",
    icon: "/images/photo5.jpg",
    image: "/icons/dom.svg",
    baloon: "/icons/baloon.svg",
    },
    {
      title: "Why do we use it?",
      text_1: "It is a long established fact that a reader will be distracted by the readable content",
      text_2: "It is a long established fact that a reader will be distracted by the readable content",
      text_3: "It is a long established fact that a reader will be distracted by the readable content",
      icon: "/images/photo6.jpg",
      image: "/icons/coconaut.svg",
      baloon: "/icons/baloon.svg",
      },
      {
        title: "Why do we use it?",
        text_1: "It is a long established fact that a reader will be distracted by the readable content",
        text_2: "It is a long established fact that a reader will be distracted by the readable content",
        text_3: "It is a long established fact that a reader will be distracted by the readable content",
        icon: "/images/photo3.jpg",
        image: "/icons/hotel.svg",
        baloon: "/icons/baloon.svg",
        },
        {
          title: "Why do we use it?",
          text_1: "It is a long established fact that a reader will be distracted by the readable content",
          text_2: "It is a long established fact that a reader will be distracted by the readable content",
          text_3: "It is a long established fact that a reader will be distracted by the readable content",
          icon: "/images/photo4.jpg",
          image: "/icons/hat.svg",
          baloon: "/icons/baloon.svg",
  },
];